"""Generated protobuf/grpc stubs. Regenerated by scripts/gen_proto.sh -- not
checked in (see .gitignore).

The generated *_grpc.py imports its sibling pb2 module via the proto package
path (``from livestt.v1 import asr_pb2``), not a relative import, so this
directory must be importable as a root in its own right.
"""

import os
import sys

_PB_DIR = os.path.dirname(__file__)
if _PB_DIR not in sys.path:
    sys.path.insert(0, _PB_DIR)
