# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from livestt.v1 import asr_pb2 as livestt_dot_v1_dot_asr__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in livestt/v1/asr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingASRStub:
    """The RPC *is* the session. One phone call = one Transcribe stream = one logical
    ASR session. There is deliberately no session_id and no server-side registry:
    nothing can be resumed after a stream ends, because the encoder cache lives in
    a worker process that dies with the stream. A session_id field would only
    invite a resume RPC that cannot be implemented.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.stream_stream(
                '/livestt.v1.StreamingASR/Transcribe',
                request_serializer=livestt_dot_v1_dot_asr__pb2.TranscriptionRequest.SerializeToString,
                response_deserializer=livestt_dot_v1_dot_asr__pb2.TranscriptionEvent.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/livestt.v1.StreamingASR/GetServerInfo',
                request_serializer=livestt_dot_v1_dot_asr__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=livestt_dot_v1_dot_asr__pb2.ServerInfoResponse.FromString,
                _registered_method=True)


class StreamingASRServicer:
    """The RPC *is* the session. One phone call = one Transcribe stream = one logical
    ASR session. There is deliberately no session_id and no server-side registry:
    nothing can be resumed after a stream ends, because the encoder cache lives in
    a worker process that dies with the stream. A session_id field would only
    invite a resume RPC that cannot be implemented.
    """

    def Transcribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=livestt_dot_v1_dot_asr__pb2.TranscriptionRequest.FromString,
                    response_serializer=livestt_dot_v1_dot_asr__pb2.TranscriptionEvent.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=livestt_dot_v1_dot_asr__pb2.ServerInfoRequest.FromString,
                    response_serializer=livestt_dot_v1_dot_asr__pb2.ServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'livestt.v1.StreamingASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('livestt.v1.StreamingASR', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingASR:
    """The RPC *is* the session. One phone call = one Transcribe stream = one logical
    ASR session. There is deliberately no session_id and no server-side registry:
    nothing can be resumed after a stream ends, because the encoder cache lives in
    a worker process that dies with the stream. A session_id field would only
    invite a resume RPC that cannot be implemented.
    """

    @staticmethod
    def Transcribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/livestt.v1.StreamingASR/Transcribe',
            livestt_dot_v1_dot_asr__pb2.TranscriptionRequest.SerializeToString,
            livestt_dot_v1_dot_asr__pb2.TranscriptionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livestt.v1.StreamingASR/GetServerInfo',
            livestt_dot_v1_dot_asr__pb2.ServerInfoRequest.SerializeToString,
            livestt_dot_v1_dot_asr__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
